"""
build_paper_tables.py (P0.7)

Reads every result JSON under prism_results/experiments/ and emits LaTeX
\\input-able tables with Wilson 95% CIs. Writing the paper becomes a
copy-paste job; no manual numerical transcription.

Emitted tables (into --out-dir, default: paper/tables/):
  main_attacks.tex            — PRISM attacks (FGSM/PGD/Square/AutoAttack/CW) 5-seed pooled
  adaptive_pgd.tex            — λ sweep TPR/FPR with tier FPRs
  ablation.tex                — Full vs No-L0 vs No-MoE vs TDA-only (+ ensemble-no-TDA if present)
  baselines.tex               — LID / Mahalanobis / ODIN / Energy vs PRISM at matched FPR
  campaign.tex                — SACD scenarios, L0-on vs L0-off ASR gap
  recovery.tex                — TAMSH recovery_accuracy per strategy

Seed aggregation:
  If multiple `results_<family>_seed<N>.json` files exist, per-cell TPR/FPR
  counts are summed and a single Wilson CI is computed on the pooled
  contingency. Falls back gracefully if only one seed is present.

USAGE
-----
  cd prism/
  python scripts/build_paper_tables.py
  python scripts/build_paper_tables.py --results-dir ../prism_results --out-dir paper/tables/
"""
import json
import os
import re
import argparse
from glob import glob
from collections import defaultdict

import numpy as np


def wilson_ci(k: int, n: int, z: float = 1.96):
    if n == 0:
        return (0.0, 1.0)
    p = k / n
    denom = 1 + z**2 / n
    centre = (p + z**2 / (2 * n)) / denom
    margin = (z * np.sqrt(p * (1 - p) / n + z**2 / (4 * n**2))) / denom
    return (max(0.0, centre - margin), min(1.0, centre + margin))


def _fmt(val, prec=3):
    if val is None:
        return '--'
    return f"{val:.{prec}f}"


def _fmt_ci(lo, hi, prec=3):
    return f"[{_fmt(lo, prec)}, {_fmt(hi, prec)}]"


def _load_json(path):
    with open(path, 'r', encoding='utf-8') as f:
        return json.load(f)


# ────────────────────────────────────────────────────────────────────────────
# Pool helpers
# ────────────────────────────────────────────────────────────────────────────

def _pool_counts(entries):
    """Sum TP/FP/FN/TN across entries; return dict + pooled Wilson CIs."""
    tp = sum(e.get('TP', 0) for e in entries)
    fp = sum(e.get('FP', 0) for e in entries)
    fn = sum(e.get('FN', 0) for e in entries)
    tn = sum(e.get('TN', 0) for e in entries)
    n_adv = tp + fn
    n_clean = fp + tn
    tpr = tp / max(n_adv, 1)
    fpr = fp / max(n_clean, 1)
    tpr_lo, tpr_hi = wilson_ci(tp, n_adv)
    fpr_lo, fpr_hi = wilson_ci(fp, n_clean)
    return {
        'TPR': tpr, 'TPR_CI': (tpr_lo, tpr_hi),
        'FPR': fpr, 'FPR_CI': (fpr_lo, fpr_hi),
        'TP': tp, 'FP': fp, 'FN': fn, 'TN': tn,
        'n_adv': n_adv, 'n_clean': n_clean,
        'n_seeds': len(entries),
    }


# ────────────────────────────────────────────────────────────────────────────
# Table: main attacks (PRISM)
# ────────────────────────────────────────────────────────────────────────────

def table_main_attacks(results_dir):
    paths = sorted(glob(os.path.join(
        results_dir, 'experiments', 'evaluation', 'results_paper_seed*.json')))
    # Also merge CW results if present
    # Accept both per-seed files (results_cw_seed*.json) and the pooled-seed
    # file produced by run_vastai_full.sh (results_cw_n<N>_ms<S>.json).
    cw_paths = sorted(set(
        glob(os.path.join(results_dir, 'experiments', 'evaluation', 'results_cw_seed*.json'))
        + glob(os.path.join(results_dir, 'experiments', 'evaluation', 'results_cw_n*_ms*.json'))
    ))
    # Also n1000 fast pool
    pool_paths = sorted(glob(os.path.join(
        results_dir, 'experiments', 'evaluation', 'results_fast_n1000_ms*.json')))

    per_attack = defaultdict(list)
    for p in paths + pool_paths:
        d = _load_json(p)
        for atk, entry in d.items():
            if atk.startswith('_') or not isinstance(entry, dict): continue
            if 'TP' in entry:
                per_attack[atk].append(entry)
    for p in cw_paths:
        d = _load_json(p)
        for atk, entry in d.items():
            if atk.startswith('_') or not isinstance(entry, dict): continue
            if 'CW' in atk or atk == 'CW':
                per_attack[atk].append(entry)

    if not per_attack:
        return "% No main-attack results found.\n"

    lines = [
        "% Auto-generated by scripts/build_paper_tables.py — do not edit by hand.",
        "\\begin{tabular}{lcccc}",
        "\\toprule",
        "Attack & TPR & 95\\% CI & FPR & $n$ \\\\",
        "\\midrule",
    ]
    order = ['FGSM', 'PGD', 'Square', 'AutoAttack', 'CW', 'CW_L2']
    for atk in order + [a for a in per_attack if a not in order]:
        if atk not in per_attack: continue
        pooled = _pool_counts(per_attack[atk])
        lo, hi = pooled['TPR_CI']
        lines.append(
            f"{atk} & {_fmt(pooled['TPR'])} & {_fmt_ci(lo, hi)} & "
            f"{_fmt(pooled['FPR'])} & {pooled['n_adv']} \\\\"
        )
    lines += ["\\bottomrule", "\\end{tabular}"]
    return '\n'.join(lines) + '\n'


# ────────────────────────────────────────────────────────────────────────────
# Table: adaptive PGD
# ────────────────────────────────────────────────────────────────────────────

def table_adaptive_pgd(results_dir):
    paths = sorted(glob(os.path.join(
        results_dir, 'experiments', 'evaluation', 'results_adaptive_pgd_seed*.json')))
    per_lambda = defaultdict(list)
    for p in paths:
        d = _load_json(p)
        for key, entry in d.items():
            if key.startswith('_') or not isinstance(entry, dict): continue
            m = re.match(r'AdaptivePGD_lambda_([0-9.]+)', key)
            if m: per_lambda[float(m.group(1))].append(entry)
    if not per_lambda:
        return "% No adaptive-PGD results found.\n"

    lines = [
        "% Auto-generated by scripts/build_paper_tables.py",
        "\\begin{tabular}{cccc}",
        "\\toprule",
        "$\\lambda$ & TPR & 95\\% CI & FPR \\\\",
        "\\midrule",
    ]
    for lam in sorted(per_lambda):
        pooled = _pool_counts(per_lambda[lam])
        lo, hi = pooled['TPR_CI']
        lines.append(
            f"{lam:.1f} & {_fmt(pooled['TPR'])} & {_fmt_ci(lo, hi)} & {_fmt(pooled['FPR'])} \\\\"
        )
    lines += ["\\bottomrule", "\\end{tabular}"]
    return '\n'.join(lines) + '\n'


# ────────────────────────────────────────────────────────────────────────────
# Table: ablation
# ────────────────────────────────────────────────────────────────────────────

def table_ablation(results_dir):
    path = os.path.join(results_dir, 'experiments', 'ablation',
                        'results_ablation_multiseed.json')
    if not os.path.exists(path):
        return "% No ablation multi-seed file found.\n"
    d = _load_json(path)
    agg = d.get('aggregate', {})
    stat = d.get('statistical_tests', {})
    if not agg:
        return "% aggregate key missing.\n"

    lines = [
        "% Auto-generated by scripts/build_paper_tables.py",
        "\\begin{tabular}{lccc}",
        "\\toprule",
        "Configuration & Mean TPR & $\\Delta$ vs Full & $p$-value \\\\",
        "\\midrule",
    ]
    for cfg_name, cfg_agg in agg.items():
        tpr_mean = cfg_agg.get('mean_TPR', cfg_agg.get('TPR_mean'))
        delta = stat.get(cfg_name, {}).get('delta_tpr', None)
        pval  = stat.get(cfg_name, {}).get('p_value', None)
        delta_s = (f"{delta:+.4f}" if isinstance(delta, (int, float)) else "--")
        pval_s  = (f"{pval:.3f}" if isinstance(pval, (int, float)) else "--")
        lines.append(
            f"{cfg_name} & {_fmt(tpr_mean, 4)} & {delta_s} & {pval_s} \\\\"
        )
    lines += ["\\bottomrule", "\\end{tabular}"]
    return '\n'.join(lines) + '\n'


# ────────────────────────────────────────────────────────────────────────────
# Table: baselines
# ────────────────────────────────────────────────────────────────────────────

def table_baselines(results_dir):
    paths = sorted(glob(os.path.join(
        results_dir, 'experiments', 'evaluation', 'results_baselines*seed*.json')))
    paths += sorted(glob(os.path.join(
        results_dir, 'experiments', 'evaluation', 'results_baselines.json')))
    per_det_atk = defaultdict(lambda: defaultdict(list))
    for p in paths:
        d = _load_json(p)
        for det, attacks in d.items():
            if det.startswith('_') or not isinstance(attacks, dict): continue
            for atk, entry in attacks.items():
                if isinstance(entry, dict) and 'TP' in entry:
                    per_det_atk[det][atk].append(entry)
    if not per_det_atk:
        return "% No baseline results found.\n"

    lines = [
        "% Auto-generated by scripts/build_paper_tables.py",
        "\\begin{tabular}{llccc}",
        "\\toprule",
        "Detector & Attack & TPR & 95\\% CI & FPR \\\\",
        "\\midrule",
    ]
    for det in sorted(per_det_atk):
        for atk in sorted(per_det_atk[det]):
            pooled = _pool_counts(per_det_atk[det][atk])
            lo, hi = pooled['TPR_CI']
            lines.append(
                f"{det} & {atk} & {_fmt(pooled['TPR'])} & "
                f"{_fmt_ci(lo, hi)} & {_fmt(pooled['FPR'])} \\\\"
            )
    lines += ["\\bottomrule", "\\end{tabular}"]
    return '\n'.join(lines) + '\n'


# ────────────────────────────────────────────────────────────────────────────
# Table: campaign (SACD)
# ────────────────────────────────────────────────────────────────────────────

def table_campaign(results_dir):
    paths = sorted(glob(os.path.join(
        results_dir, 'experiments', 'campaign', 'results_campaign*seed*.json')))
    paths += sorted(glob(os.path.join(
        results_dir, 'experiments', 'evaluation', 'results_campaign*.json')))
    per_scen = defaultdict(lambda: {'l0_on': [], 'l0_off': [], 'l0_active_frac': []})
    for p in paths:
        d = _load_json(p)
        for scen, v in d.items():
            if scen.startswith('_') or not isinstance(v, dict): continue
            if 'l0_on' in v and 'l0_off' in v:
                per_scen[scen]['l0_on'].append(v['l0_on']['ASR'])
                per_scen[scen]['l0_off'].append(v['l0_off']['ASR'])
                per_scen[scen]['l0_active_frac'].append(
                    v['l0_on'].get('l0_active_fraction', None))
    if not per_scen:
        return "% No campaign results found.\n"

    lines = [
        "% Auto-generated by scripts/build_paper_tables.py",
        "\\begin{tabular}{lccc}",
        "\\toprule",
        "Scenario & ASR (L0 off) & ASR (L0 on) & $\\Delta$ (pp) \\\\",
        "\\midrule",
    ]
    for scen in sorted(per_scen):
        off = np.mean(per_scen[scen]['l0_off']) if per_scen[scen]['l0_off'] else 0
        on  = np.mean(per_scen[scen]['l0_on']) if per_scen[scen]['l0_on'] else 0
        delta = 100.0 * (off - on)
        scen_tex = scen.replace('_', '\\_')
        lines.append(
            f"{scen_tex} & {_fmt(off)} & {_fmt(on)} & {delta:+.2f} \\\\"
        )
    lines += ["\\bottomrule", "\\end{tabular}"]
    return '\n'.join(lines) + '\n'


# ────────────────────────────────────────────────────────────────────────────
# Table: recovery (TAMSH)
# ────────────────────────────────────────────────────────────────────────────

def table_recovery(results_dir):
    paths = sorted(glob(os.path.join(
        results_dir, 'experiments', 'recovery', 'results_recovery*seed*.json')))
    paths += sorted(glob(os.path.join(
        results_dir, 'experiments', 'evaluation', 'results_recovery*.json')))
    per_strat = defaultdict(list)
    for p in paths:
        d = _load_json(p)
        for k, v in d.items():
            if k.startswith('_') or not isinstance(v, dict): continue
            if 'recovery_accuracy' in v:
                per_strat[k].append(v)
    if not per_strat:
        return "% No recovery results found.\n"

    lines = [
        "% Auto-generated by scripts/build_paper_tables.py",
        "\\begin{tabular}{lccc}",
        "\\toprule",
        "Strategy & Recovery Acc. & 95\\% CI & Availability \\\\",
        "\\midrule",
    ]
    for strat in ['reject', 'passthrough', 'tamsh']:
        if strat not in per_strat: continue
        entries = per_strat[strat]
        n_correct = sum(e.get('n_correct', 0) for e in entries)
        n_l3      = sum(e.get('n_l3', 0) for e in entries)
        acc = n_correct / max(n_l3, 1)
        lo, hi = wilson_ci(n_correct, n_l3)
        avail = np.mean([e.get('availability', 0) for e in entries])
        lines.append(
            f"{strat} & {_fmt(acc)} & {_fmt_ci(lo, hi)} & {_fmt(avail)} \\\\"
        )
    lines += ["\\bottomrule", "\\end{tabular}"]
    return '\n'.join(lines) + '\n'


def main():
    parser = argparse.ArgumentParser(description="Build LaTeX tables from prism_results (P0.7)")
    parser.add_argument('--config', default=None,
                        help='YAML config path (accepted for API symmetry; '
                             'build_paper_tables does not read src.config).')
    parser.add_argument('--results-dir', default='../prism_results',
                        help='Path to prism_results/ (relative to prism/ or absolute).')
    parser.add_argument('--out-dir', default='paper/tables',
                        help='Output directory for .tex files.')
    args = parser.parse_args()

    os.makedirs(args.out_dir, exist_ok=True)

    outputs = {
        'main_attacks.tex': table_main_attacks(args.results_dir),
        'adaptive_pgd.tex': table_adaptive_pgd(args.results_dir),
        'ablation.tex':     table_ablation(args.results_dir),
        'baselines.tex':    table_baselines(args.results_dir),
        'campaign.tex':     table_campaign(args.results_dir),
        'recovery.tex':     table_recovery(args.results_dir),
    }
    for fname, content in outputs.items():
        path = os.path.join(args.out_dir, fname)
        with open(path, 'w', encoding='utf-8') as f:
            f.write(content)
        print(f"  wrote {path}  ({len(content.splitlines())} lines)")


if __name__ == '__main__':
    main()
